name: Build GMP

on:
  workflow_call:
    inputs:
      os:
        description: 'Operating System'
        required: true
        type: string
      arch:
        description: 'Architecture'
        required: true
        type: string
      gmp-version:
        description: 'GMP version'
        required: true
        type: string
      mpfr-version:
        description: 'MPFR version'
        required: true
        type: string
      build-type:
        description: 'Build type (shared or static)'
        required: true
        type: string
        default: 'shared'

  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: linux
      arch:
        description: 'Architecture'
        required: true
        default: x64
      gmp-version:
        description: 'GMP version'
        required: true
        default: 6.3.0
      mpfr-version:
        description: 'MPFR version'
        required: true
        default: 4.2.1
      build-type:
        description: 'Build type (shared or static)'
        required: true
        default: 'shared'

jobs:
  build:
    runs-on: ${{ (inputs.os == 'osx' || inputs.os == 'ios') && (inputs.arch == 'x64' && 'macos-13' || 'macos-latest') || 'ubuntu-latest' }}
    env:
      GMP_CONFIGURE: ${{ inputs.os == 'browser' && 'emconfigure ./configure' || './configure' }}
      BUILD_TYPE: ${{ inputs.build-type }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set environment variables
        run: |
          echo "TARGET=${{ inputs.os }}-${{ inputs.arch }}" >> $GITHUB_ENV
          GMP_CONFIGURE_ARGS="--enable-cxx --enable-fat"
          echo "GMP_SO=libgmp.so.10" >> $GITHUB_ENV
          echo "GMP_CPP_SO=libgmpxx.so.4" >> $GITHUB_ENV
          echo "MPFR_SO=libmpfr.so.6" >> $GITHUB_ENV
      
          case "${{ inputs.os }}" in
            "linux")
      
              case "${{ inputs.arch }}" in
                "x64")
                  echo "HOST=x86_64-pc-linux-gnu" >> $GITHUB_ENV
                  echo "STRIP=strip --strip-unneeded" >> $GITHUB_ENV
                  echo "TEST_CC=gcc" >> $GITHUB_ENV
                  ;;
                "x86")
                  echo "HOST=i686-pc-linux-gnu" >> $GITHUB_ENV
                  echo "STRIP=strip --strip-unneeded" >> $GITHUB_ENV
                  echo "TEST_CC=gcc -m32" >> $GITHUB_ENV
                  ;;
                "arm64")
                  echo "HOST=aarch64-linux-gnu" >> $GITHUB_ENV
                  echo "STRIP=aarch64-linux-gnu-strip --strip-unneeded" >> $GITHUB_ENV
                  echo "TEST_CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
                  ;;
                "arm")
                  echo "HOST=arm-linux-gnueabihf" >> $GITHUB_ENV
                  echo "STRIP=arm-linux-gnueabihf-strip --strip-unneeded" >> $GITHUB_ENV
                  echo "TEST_CC=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
                  ;;
              esac
              ;;
      
            "linux-musl")      
              case "${{ inputs.arch }}" in
                "x64")
                  echo "HOST=x86_64-linux-musl" >> $GITHUB_ENV
                  echo "STRIP=strip --strip-unneeded" >> $GITHUB_ENV
                  echo "TEST_CC=musl-gcc" >> $GITHUB_ENV
                  ;;
                "arm64")
                  echo "HOST=aarch64-unknown-linux-musl" >> $GITHUB_ENV
                  echo "STRIP=aarch64-unknown-linux-musl-strip --strip-unneeded" >> $GITHUB_ENV
                  echo "TEST_CC=aarch64-unknown-linux-musl-gcc" >> $GITHUB_ENV
                  ;;
              esac
              ;;

            "win")
              echo "GMP_SO=libgmp-10.dll" >> $GITHUB_ENV
              echo "GMP_CPP_SO=libgmpxx-4.dll" >> $GITHUB_ENV
              echo "MPFR_SO=libmpfr-6.dll" >> $GITHUB_ENV
      
              case "${{ inputs.arch }}" in
                "x64")
                  echo "HOST=x86_64-w64-mingw32" >> $GITHUB_ENV
                  echo "STRIP=x86_64-w64-mingw32-strip --strip-unneeded" >> $GITHUB_ENV
                  echo "TEST_CC=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV
                  ;;
                "x86")
                  echo "HOST=i686-w64-mingw32" >> $GITHUB_ENV
                  echo "STRIP=i686-w64-mingw32-strip --strip-unneeded" >> $GITHUB_ENV
                  echo "TEST_CC=i686-w64-mingw32-gcc" >> $GITHUB_ENV
                  ;;
              esac
              ;;
      
            "android")
              echo "GMP_SO=libgmp.so" >> $GITHUB_ENV
              echo "GMP_CPP_SO=libgmpxx.so" >> $GITHUB_ENV
              echo "MPFR_SO=libmpfr.so" >> $GITHUB_ENV
              echo "STRIP=${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip --strip-unneeded" >> $GITHUB_ENV
      
              case "${{ inputs.arch }}" in
                "x64")
                  HOST=x86_64-linux-android
                  ;;
                "arm64")
                  HOST=aarch64-linux-android
                  ;;
                "x86")
                  HOST=i686-linux-android
                  ;;
                "arm")
                  HOST=armv7a-linux-android
                  ;;
              esac
              echo "HOST=$HOST" >> $GITHUB_ENV
              GMP_CONFIGURE_ARGS="${GMP_CONFIGURE_ARGS} --with-pic"
              ARGS="--target=${HOST}21 --sysroot=${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/sysroot -pie"
              echo "TEST_CC=${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang ${ARGS} -fPIC" >> $GITHUB_ENV
              echo "CC=${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang ${ARGS} -fPIC" >> $GITHUB_ENV
              echo "CXX=${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ ${ARGS} -fPIC" >> $GITHUB_ENV
              ;;
      
            "osx")
              echo "GMP_SO=libgmp.dylib" >> $GITHUB_ENV
              echo "GMP_CPP_SO=libgmpxx.dylib" >> $GITHUB_ENV
              echo "MPFR_SO=libmpfr.dylib" >> $GITHUB_ENV
              echo "STRIP=strip -x" >> $GITHUB_ENV
      
              case "${{ inputs.arch }}" in
                "arm64")
                  echo "HOST=aarch64-apple-darwin" >> $GITHUB_ENV
                  echo "TEST_CC=clang -arch arm64" >> $GITHUB_ENV
                  ;;
                "x64")
                  echo "HOST=x86_64-apple-darwin" >> $GITHUB_ENV
                  echo "TEST_CC=clang" >> $GITHUB_ENV
                  echo "LDFLAGS=-ld_classic" >> $GITHUB_ENV
                  if [ "${{ env.BUILD_TYPE }}" == "static" ]; then
                    GMP_CONFIGURE_ARGS="${GMP_CONFIGURE_ARGS//--enable-fat/--disable-assembly}" # macOS static does not support fat binaries & assembly
                  fi
                  ;;
              esac
              ;;
      
            "ios")
              BUILD_TYPE=static # iOS does not support shared libraries
              echo "BUILD_TYPE=static" >> $GITHUB_ENV
              echo "HOST=aarch64-apple-ios" >> $GITHUB_ENV
              echo "STRIP=strip -x" >> $GITHUB_ENV
              echo "CFLAGS=-arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -miphoneos-version-min=12.0" >> $GITHUB_ENV
              echo "LDFLAGS=-arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -miphoneos-version-min=12.0" >> $GITHUB_ENV
              echo "TEST_CC=xcrun -sdk iphoneos clang -arch arm64 -isysroot \$(xcrun --sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV
              GMP_CONFIGURE_ARGS="${GMP_CONFIGURE_ARGS//--enable-fat/--disable-assembly}" # iOS does not support fat binaries & assembly
              ;;
      
            "browser")
              BUILD_TYPE=static # WebAssembly does not support shared libraries
              echo "BUILD_TYPE=static" >> $GITHUB_ENV
              echo "HOST=none" >> $GITHUB_ENV
              echo "STRIP=strip" >> $GITHUB_ENV
              echo "TEST_CC=emcc" >> $GITHUB_ENV
              GMP_CONFIGURE_ARGS="${GMP_CONFIGURE_ARGS//--enable-fat/--disable-assembly}" # WebAssembly does not support fat binaries & assembly
              ;;

            *)
              echo "Error: Unsupported OS-Architecture combination: ${{ inputs.os }}-${{ inputs.arch }}"
              exit 1
              ;;
          esac
          case "$BUILD_TYPE" in
            "shared")
              echo "GMP_CONFIGURE_ARGS=${GMP_CONFIGURE_ARGS}" >> $GITHUB_ENV
              echo "BUILD_TYPE_ARGS=--enable-shared --disable-static" >> $GITHUB_ENV
              ;;
            "static")
              echo "GMP_CONFIGURE_ARGS=${GMP_CONFIGURE_ARGS}" >> $GITHUB_ENV
              echo "BUILD_TYPE_ARGS=--enable-static --disable-shared" >> $GITHUB_ENV
              echo "GMP_SO=libgmp.a" >> $GITHUB_ENV
              echo "GMP_CPP_SO=libgmpxx.a" >> $GITHUB_ENV
              echo "MPFR_SO=libmpfr.a" >> $GITHUB_ENV
              ;;
            *)
              echo "Error: Unsupported build type: ${{ inputs.build-type }}"
              exit 1
            ;;
          esac

      - name: Install Toolchain (arch-specific)
        run: |
          case "$TARGET" in
            "linux-x64")
              ;;
            "linux-x86")
              sudo apt-get update
              sudo apt-get install -y gcc-multilib g++-multilib
              ;;
            "linux-arm64")
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends qemu-user gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
              ;;
            "linux-arm")
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends qemu-user gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
              ;;
            "linux-musl-x64")
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends musl-tools
              ;;
            "linux-musl-arm64")
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends musl-tools qemu-user
              sudo mkdir -p /opt/x-tools
              wget -nv https://github.com/musl-cross/musl-cross/releases/download/20241103/aarch64-unknown-linux-musl.tar.xz
              sudo tar -xf aarch64-unknown-linux-musl.tar.xz -C /opt/x-tools
              ls -l /opt/x-tools/aarch64-unknown-linux-musl/bin/
              /opt/x-tools/aarch64-unknown-linux-musl/bin/aarch64-unknown-linux-musl-gcc --version
              echo "/opt/x-tools/aarch64-unknown-linux-musl/bin" >> $GITHUB_PATH
              ;;
            "win-x86")
              sudo dpkg --add-architecture i386
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends mingw-w64
              sudo apt-get install -y wine32:i386
              ;;
            "win-x64")
              sudo apt-get update
              sudo apt-get install -y --no-install-recommends mingw-w64 wine
              ;;
            "android-x64" | "android-arm64" | "android-x86" | "android-arm")
              ;;
            "osx-arm64" | "osx-x64" | "ios-arm64")
              echo "No toolchain installation needed on macOS/iOS."
              ;;
            "browser-wasm")
              git clone --depth 1 https://github.com/emscripten-core/emsdk.git
              cd emsdk
              ./emsdk install latest
              ./emsdk activate latest
              echo "${{ github.workspace }}/emsdk" >> $GITHUB_PATH
              echo "${{ github.workspace }}/emsdk/upstream/emscripten" >> $GITHUB_PATH
              ;;
            *)
              echo "Error: Unsupported OS-Architecture combination: $TARGET"
              exit 1
              ;;
          esac

      - name: Download GMP Source
        run: |
          wget -nv https://mirrors.nju.edu.cn/gnu/gmp/gmp-${{ inputs.gmp-version }}.tar.xz
          tar -xf gmp-${{ inputs.gmp-version }}.tar.xz

      - name: Configure GMP
        run: |
          cd gmp-${{ inputs.gmp-version }}
          ${{ env.GMP_CONFIGURE }} ${{ env.BUILD_TYPE_ARGS }} ${{ env.GMP_CONFIGURE_ARGS }} --host=${{ env.HOST }}

      - name: Build GMP
        run: |
          cd gmp-${{ inputs.gmp-version }}
          make -j4

      - name: Download MPFR Source
        run: |
          wget -nv https://mirrors.nju.edu.cn/gnu/mpfr/mpfr-${{ inputs.mpfr-version }}.tar.xz
          tar -xf mpfr-${{ inputs.mpfr-version }}.tar.xz

      - name: Configure MPFR
        run: |
          cd mpfr-${{ inputs.mpfr-version }}
          ./configure --with-gmp-include=${{ github.workspace }}/gmp-${{ inputs.gmp-version }} --with-gmp-lib=${{ github.workspace }}/gmp-${{ inputs.gmp-version }}/.libs ${{ env.BUILD_TYPE_ARGS }} --host=${{ env.HOST }}

      - name: Build MPFR
        run: |
          cd mpfr-${{ inputs.mpfr-version }}
          make -j4

      - name: Check .libs
        run: |
          cd ${{ github.workspace }}/gmp-${{ inputs.gmp-version }}/.libs
          ls -l
          file ${{ env.GMP_SO }}

          cd ${{ github.workspace }}/mpfr-${{ inputs.mpfr-version }}/src/.libs
          ls -l
          file ${{ env.MPFR_SO }}

      - name: Generate .lib files (Windows shared only)
        if: ${{ inputs.os == 'win' && env.BUILD_TYPE == 'shared' }}
        run: |
          cd gmp-${{ inputs.gmp-version }}/.libs
          
          if [ "$TARGET" = "win-x86" ]; then
            HOST_PREFIX=i686-w64-mingw32
          elif [ "$TARGET" = "win-x64" ]; then
            HOST_PREFIX=x86_64-w64-mingw32
          else
            echo "Error: Unsupported OS-Architecture combination: $TARGET"
            exit 1
          fi
                
          ${HOST_PREFIX}-dlltool \
            --input-def  libgmp-3.dll.def \
            --output-lib libgmp-10.lib \
            --dllname    ${{ env.GMP_SO }}
                  
          ${HOST_PREFIX}-dlltool \
            --input-def  libgmpxx-3.dll.def \
            --output-lib libgmpxx-4.lib \
            --dllname    ${{ env.GMP_SO }}
          
          echo "Converted .def files to .lib for Windows."

      - name: Dump lib dependencies(Shared Libraries only)
        if: ${{ inputs.os != 'win' && env.BUILD_TYPE != 'static' }}
        run: |
          cd gmp-${{ inputs.gmp-version }}/.libs
          case "$TARGET" in
            osx-*)
              otool -L ${{ env.GMP_SO }}
              ;;
            linux-* | android-*)
              objdump -x ${{ env.GMP_SO }} | grep NEEDED
              ;;
            *)
              echo "Error: Unsupported OS-Architecture combination: $TARGET"
              exit 1
              ;;
          esac

      - name: Strip GMP Library
        run: |
          cd gmp-${{ inputs.gmp-version }}/.libs
          ${STRIP} ${GMP_SO}
          ${STRIP} ${GMP_CPP_SO}
          ls -l
          file ${GMP_SO}

      - name: Compile Test C Program
        run: |
          ${{ env.TEST_CC }} -o factorial_gmp.exe \
            .github/workflows/factorial_gmp.c \
            -I${{ github.workspace }}/gmp-${{ inputs.gmp-version }} \
            -L${{ github.workspace }}/gmp-${{ inputs.gmp-version }}/.libs \
            -lgmp
          ls -l
          file factorial_gmp.exe

      - name: Run Test C Program
        if: ${{ inputs.os != 'android' && inputs.os != 'ios' && !(inputs.os == 'linux-musl' && inputs.arch == 'arm64') }}
        run: |
          case "$TARGET" in
            win-*)
              cp ${{ github.workspace }}/gmp-${{ inputs.gmp-version }}/.libs/${GMP_SO} .
              wine ${GITHUB_WORKSPACE}/factorial_gmp.exe
              ;;
            "linux-x64" | "linux-x86")
              LD_LIBRARY_PATH=${{ github.workspace }}/gmp-${{ inputs.gmp-version }}/.libs ./factorial_gmp.exe
              ;;
            "linux-arm64")
              LD_LIBRARY_PATH=${{ github.workspace }}/gmp-${{ inputs.gmp-version }}/.libs qemu-aarch64 -L /usr/aarch64-linux-gnu/ ./factorial_gmp.exe
              ;;
            "linux-arm")
              LD_LIBRARY_PATH=${{ github.workspace }}/gmp-${{ inputs.gmp-version }}/.libs qemu-arm -L /usr/arm-linux-gnueabihf/ ./factorial_gmp.exe
              ;;
            "linux-musl-x64")
              LD_LIBRARY_PATH=${{ github.workspace }}/gmp-${{ inputs.gmp-version }}/.libs ./factorial_gmp.exe
              ;;
            osx-*)
              DYLD_LIBRARY_PATH=${{ github.workspace }}/gmp-${{ inputs.gmp-version }}/.libs ./factorial_gmp.exe
              ;;
            browser-wasm)
              node ./factorial_gmp.exe
              ;;
            *)
              echo "Error: Unsupported OS-Architecture combination: $TARGET"
              exit 1
              ;;
          esac

      - name: Prepare Artifact folder
        run: |
          mkdir -p artifacts/bin artifacts/include artifacts/misc artifacts/test
          cp gmp-${{ inputs.gmp-version }}/gmp.h ./artifacts/include
          cp gmp-${{ inputs.gmp-version }}/gmpxx.h ./artifacts/include
          cp -L gmp-${{ inputs.gmp-version }}/.libs/${{ env.GMP_SO }}     ./artifacts/bin
          cp -L gmp-${{ inputs.gmp-version }}/.libs/${{ env.GMP_CPP_SO }} ./artifacts/bin
          cp -L mpfr-${{ inputs.mpfr-version }}/src/.libs/${{ env.MPFR_SO }} ./artifacts/bin
          cp gmp-${{ inputs.gmp-version }}/.libs/*.lib ./artifacts/misc || true
          cp gmp-${{ inputs.gmp-version }}/.libs/*.def ./artifacts/misc || true
          cp gmp-${{ inputs.gmp-version }}/.libs/*.lai ./artifacts/misc
          cp factorial_gmp.* ./artifacts/test

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gmp-${{ inputs.os }}-${{ inputs.arch }}
          path: artifacts